/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"
	json "encoding/json"
	"fmt"

	v1 "github.com/edgelive/def/apis/heartbeat/v1"
	heartbeatv1 "github.com/edgelive/def/applyconfiguration/heartbeat/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeHeartbeats implements HeartbeatInterface
type FakeHeartbeats struct {
	Fake *FakeHeartbeatV1
	ns   string
}

var heartbeatsResource = v1.SchemeGroupVersion.WithResource("heartbeats")

var heartbeatsKind = v1.SchemeGroupVersion.WithKind("Heartbeat")

// Get takes name of the heartbeat, and returns the corresponding heartbeat object, and an error if there is any.
func (c *FakeHeartbeats) Get(ctx context.Context, name string, options metav1.GetOptions) (result *v1.Heartbeat, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(heartbeatsResource, c.ns, name), &v1.Heartbeat{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.Heartbeat), err
}

// List takes label and field selectors, and returns the list of Heartbeats that match those selectors.
func (c *FakeHeartbeats) List(ctx context.Context, opts metav1.ListOptions) (result *v1.HeartbeatList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(heartbeatsResource, heartbeatsKind, c.ns, opts), &v1.HeartbeatList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1.HeartbeatList{ListMeta: obj.(*v1.HeartbeatList).ListMeta}
	for _, item := range obj.(*v1.HeartbeatList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested heartbeats.
func (c *FakeHeartbeats) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(heartbeatsResource, c.ns, opts))

}

// Create takes the representation of a heartbeat and creates it.  Returns the server's representation of the heartbeat, and an error, if there is any.
func (c *FakeHeartbeats) Create(ctx context.Context, heartbeat *v1.Heartbeat, opts metav1.CreateOptions) (result *v1.Heartbeat, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(heartbeatsResource, c.ns, heartbeat), &v1.Heartbeat{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.Heartbeat), err
}

// Update takes the representation of a heartbeat and updates it. Returns the server's representation of the heartbeat, and an error, if there is any.
func (c *FakeHeartbeats) Update(ctx context.Context, heartbeat *v1.Heartbeat, opts metav1.UpdateOptions) (result *v1.Heartbeat, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(heartbeatsResource, c.ns, heartbeat), &v1.Heartbeat{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.Heartbeat), err
}

// Delete takes name of the heartbeat and deletes it. Returns an error if one occurs.
func (c *FakeHeartbeats) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(heartbeatsResource, c.ns, name, opts), &v1.Heartbeat{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeHeartbeats) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(heartbeatsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1.HeartbeatList{})
	return err
}

// Patch applies the patch and returns the patched heartbeat.
func (c *FakeHeartbeats) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.Heartbeat, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(heartbeatsResource, c.ns, name, pt, data, subresources...), &v1.Heartbeat{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.Heartbeat), err
}

// Apply takes the given apply declarative configuration, applies it and returns the applied heartbeat.
func (c *FakeHeartbeats) Apply(ctx context.Context, heartbeat *heartbeatv1.HeartbeatApplyConfiguration, opts metav1.ApplyOptions) (result *v1.Heartbeat, err error) {
	if heartbeat == nil {
		return nil, fmt.Errorf("heartbeat provided to Apply must not be nil")
	}
	data, err := json.Marshal(heartbeat)
	if err != nil {
		return nil, err
	}
	name := heartbeat.Name
	if name == nil {
		return nil, fmt.Errorf("heartbeat.Name must be provided to Apply")
	}
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(heartbeatsResource, c.ns, *name, types.ApplyPatchType, data), &v1.Heartbeat{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.Heartbeat), err
}
